services:
  invoicerr:
    image: ghcr.io/invoicerr-app/invoicerr:v1.4.1f
    environment:
      DATABASE_URL: ${DATABASE_URL}

      APP_URL: ${APP_URL}
      CORS_ORIGINS: ${CORS_ORIGINS}

      SMTP_HOST: ${SMTP_HOST}
      SMTP_USER: ${SMTP_USER}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SECURE: ${SMTP_SECURE}

      OIDC_ISSUER: ${OIDC_ISSUER}
      OIDC_NAME: ${OIDC_NAME}

      OIDC_AUTHORIZATION_ENDPOINT: ${OIDC_AUTHORIZATION_ENDPOINT}
      OIDC_TOKEN_ENDPOINT: ${OIDC_TOKEN_ENDPOINT}
      OIDC_USERINFO_ENDPOINT: ${OIDC_USERINFO_ENDPOINT}
      OIDC_TOKEN_REVOKE_ENDPOINT: ${OIDC_TOKEN_REVOKE_ENDPOINT}
      OIDC_END_SESSION_ENDPOINT: ${OIDC_END_SESSION_ENDPOINT}
      OIDC_JWKS_URI: ${OIDC_JWKS_URI}

      OIDC_CLIENT_ID: ${OIDC_CLIENT_ID}
      OIDC_CLIENT_SECRET: ${OIDC_CLIENT_SECRET}

      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
