services:
  invoicerr:
    image: ghcr.io/invoicerr-app/invoicerr:latest
    environment:
      - DATABASE_URL=postgresql://invoicerr:invoicerr@invoicerr_db:5432/invoicerr_db

      - APP_URL=https://invoicerr.example.com # Required for email templates, as it redirects to the app
      - CORS_ORIGINS=http://localhost:5173,https://invoicerr.example.com # Comma-separated list of allowed origins for CORS

      # Required for email features
      - SMTP_HOST=smtp-relay.example.com
      - SMTP_USER="username@example.com"
      - SMTP_FROM="user-from@example.com" # Not required if SMTP_USER is the same as SMTP_FROM
      - SMTP_PASSWORD="your_smtp_password"
      - SMTP_PORT=587 # Change this to your SMTP port (default is 587 for TLS)
      - SMTP_SECURE=false # Set to true if your SMTP server requires a secure connection (default is false)

      # OIDC Configuration (example for Authentik)
      - OIDC_ISSUER="https://auth.chevrier.dev"
      - OIDC_NAME="Pocket ID"
      # Endpoints for OIDC
      - OIDC_AUTHORIZATION_ENDPOINT="https://auth.chevrier.dev/authorize"
      - OIDC_TOKEN_ENDPOINT="https://auth.chevrier.dev/token"
      - OIDC_USERINFO_ENDPOINT="https://auth.chevrier.dev/userinfo"
      - OIDC_TOKEN_REVOKE_ENDPOINT="https://auth.chevrier.dev/revoke"
      - OIDC_END_SESSION_ENDPOINT="https://auth.chevrier.dev/end_session"
      - OIDC_JWKS_URI="https://auth.chevrier.dev/.well-known/jwks.json"
      # Client ID and Secret for OIDC
      - OIDC_CLIENT_ID="your-client-id"
      - OIDC_CLIENT_SECRET="your-client-secret"

      # Optional, but recommended for docker deployments
      - JWT_SECRET="your_jwt_secret" # Used for JWT authentication, can be any random string
    depends_on:
      - invoicerr_db

  invoicerr_db:
    image: postgres:15
    environment:
      POSTGRES_USER: invoicerr
      POSTGRES_PASSWORD: invoicerr
      POSTGRES_DB: invoicerr_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
    driver: local
